In [12]:
import SimpleITK as sitk

raw_path_data = "C:/Users/longl/Documents/emA3/Benji/MitochondriaAnalysis/TIFs/Infect_Cell5_annotation/CM1.tif"


raw_data_readin= sitk.ReadImage(raw_path_data)
raw_data = sitk.GetArrayFromImage(raw_data_readin)


import cv2
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from skimage.external import tifffile as tif

def FillHole(mask):
    contours, hierarchy = cv2.findContours(mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    len_contour = len(contours)
    contour_list = []
    for i in range(len_contour):
        drawing = np.zeros_like(mask, np.uint8)  # create a black image
        img_contour = cv2.drawContours(drawing, contours, i, (255, 255, 255), -1)
        contour_list.append(img_contour)
 
    out = sum(contour_list)
    return out

def FillHole255(input_bound):
    data_tmp = input_bound
    if data_tmp.max()>1:
        mask_out = FillHole(data_tmp)
    else:
        mask_out = data_tmp
    mask_out[mask_out > 0] = 255
    return mask_out

img_num = raw_data.shape[0]

for img_i in range(0,img_num):
#     print(img_i)
    seg_raw = raw_data[img_i]
    seg_raw0 = seg_raw.astype('uint8')
    
    seg_raw0 = FillHole255(seg_raw0)
    
#     print(seg_raw0.shape)
    raw_data[img_i]=seg_raw0
    
    tif.imsave('tmp2.tif', raw_data)

In [9]:
import SimpleITK as sitk

raw_path_data = "C:/Users/longl/Documents/emA3/Benji/MitochondriaAnalysis/TIFs/Control_Cell1_annotation_8/CM_solid.tif"

raw_data_readin= sitk.ReadImage(raw_path_data)
raw_data = sitk.GetArrayFromImage(raw_data_readin)
raw_data = raw_data[0:370]

Shapexyz=raw_data.shape

print(Shapexyz)

cytoplasm = raw_data>0
CP_volume = cytoplasm.sum()
print(CP_volume)

volume = Shapexyz[0]*Shapexyz[1]*Shapexyz[2]
print(CP_volume/volume)

(370, 1180, 3068)
493110500
0.36813335057374125


In [3]:
cytoplasm = raw_data>0
CP_volume = cytoplasm.sum()
print(CP_volume)

22606838


In [5]:
volume = Shapexyz[0]*Shapexyz[1]*Shapexyz[2]
print(CP_volume/volume)

0.016877213157735996


In [8]:
print(CP_volume/volume)

0.478980262594464


In [11]:
import SimpleITK as sitk

raw_path_data = "tmp1.tif"

raw_data_readin= sitk.ReadImage(raw_path_data)
raw_data = sitk.GetArrayFromImage(raw_data_readin)

Index = raw_data>0
Volume = Index.sum()
print(Volume)



198545268


In [11]:
import SimpleITK as sitk

raw_path_data = "C:/Users/longl/Documents/emA3/Benji/MitochondriaAnalysis/TIFs/render_chimera_CC2/A4_Lipid.tif"

raw_data_readin= sitk.ReadImage(raw_path_data)
raw_data = sitk.GetArrayFromImage(raw_data_readin)

Index = raw_data>0
Volume = Index.sum()
print(Volume)



308438


In [12]:
import SimpleITK as sitk

raw_path_data = "C:/Users/longl/Documents/emA3/Benji/MitochondriaAnalysis/TIFs/render_chimera_CC2/A5_Mitoch.tif"

raw_data_readin= sitk.ReadImage(raw_path_data)
raw_data = sitk.GetArrayFromImage(raw_data_readin)

Index = raw_data>0
Volume = Index.sum()
print(Volume)



22249953


In [24]:
import numpy as np

Proportion=np.empty([4, 4])

PCC2 = np.array([13310291,0,308438,22249953])/493110500

Proportion[0] = PCC2


print(Proportion.shape)
print(Proportion)

(4, 4)
[[4.10323177e-002 0.00000000e+000 9.50837665e-004 6.85910730e-002]
 [1.78022342e-306 6.23058028e-307 9.79107872e-307 6.89807188e-307]
 [7.56594375e-307 6.23060065e-307 1.78021527e-306 8.34454050e-308]
 [1.11261027e-306 1.15706896e-306 1.33512173e-306 1.33504432e-306]]


In [1]:
import mrcfile

ModuleNotFoundError: No module named 'mrcfile'